---

- name: Link Agent
  command: "{{ nessus_agent_cli_tool }} agent link --key={{ nessus_agent_key }} --name={{ nessus_agent_name }} --groups={{ nessus_agent_groups }} --host={{ nessus_agent_host_name }} --port={{ nessus_agent_host_port }}"

- name: Register Agent link status
  shell: "{{ nessus_agent_cli_tool }} agent status"
  register: agent_link_status
  ignore_errors: false

- debug:
    msg: "Nessus Agent seems to be linked"
  when: agent_link_status.stdout.find("is linked") != -1
