---

- name: Download Nessus Agent
  get_url:
    url: "{{ nessus_agent_download_url }}"
    dest: "{{ nessus_agent_temp_dir }}/NessusAgent-7.0.3-ubuntu1110_amd64.deb"
    checksum: "{{ nessus_agent_file_checksum }}"

- name: Perform Agent installation
  command: dpkg -i "{{ nessus_agent_temp_dir }}/NessusAgent-7.0.3-ubuntu1110_amd64.deb"

- name: add the agent to the tenable
  command: "/opt/nessus_agent/sbin/nessuscli agent link --key={{ nessus_agent_key }} --name={{ nessus_agent_name }} --groups={{ nessus_agent_groups }} --host={{ nessus_agent_host_name }} --port={{ nessus_agent_host_port }}"
#  when: "'is not linked' in agent_link_status.stdout or agent_unlink_command_status.changed"

- name: Register Agent link status
  shell: "/opt/nessus_agent/sbin/nessuscli agent status"
  register: agent_link_status
  ignore_errors: true

- debug:
    msg: "Nessus Agent link status: {{agent_link_status.stdout}}"
